76 chartjs to apexchartjs
mavidurak/mentor-front-end-vue pull request #116
Opened 2021-11-28 20:29 UTC by DEONSKY

2021-12-01 17:56 UTC, teathedev requested changes

2021-12-01 17:56 UTC, teathedev commented on src/components/viewpill/AppDatasetViewPill.vue
> +  <div v-bind:class="'border rounded d-block m-1 px-1 '+color">
` isaretini kullan

2021-12-01 17:56 UTC, teathedev commented on src/views/Home/Home.vue
> +                      <apexchart ref="realtimeChart" width= "100%" height="100%" type="area" :responsive="responsive" :options="options" :series="series"></apexchart>
alt satirlara indir attr'leri. okunmuyor bu sekilde

2021-12-01 17:56 UTC, teathedev commented on src/views/Home/Home.vue
> +        console.log(this.series)
-

2021-12-01 17:56 UTC, teathedev commented on src/views/Home/Home.vue
> +        console.log(response.data)
-

2021-12-01 17:56 UTC, teathedev commented on src/views/Home/Home.vue
> +        console.log(response.data.results)
-

2021-12-01 17:56 UTC, teathedev commented on src/views/Home/Home.vue
> +        console.log(err)
-

2021-12-01 17:56 UTC, teathedev commented on src/views/Home/Home.vue
> +      // this.getDataSets()
-

2021-12-01 17:56 UTC, teathedev commented on src/views/Home/Home.vue
> +      series: [{
burasi datalar mi?

2021-12-02 22:04 UTC, DEONSKY commented on src/views/Home/Home.vue
> +      series: [{
Anladığım kadarıyla birden fazla data dizisini üst üste aynı chartda karşılaştırabildiğimiz için dökümantasyonda series ismi tercih edilmiş

2021-12-02 22:06 UTC, DEONSKY commented
Değişiklik sayısı çok artacak gibi. Ondan burada bırakıyorum ve aklıma gelen değişiklikleri issue olarak açıyorum

2021-12-13 16:47 UTC, merged